# Generated by Django 4.2.6 on 2023-10-30 10:10

from django.db import migrations, models
import website.validators


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_booking_tracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20, null=True, validators=[website.validators.validate_phonenumber]),
        ),
    ]
