# Generated by Django 4.2.6 on 2023-10-31 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_remove_customer_password_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overnightstay',
            name='status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='website.status'),
        ),
        migrations.AlterField(
            model_name='reststop',
            name='status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='website.status'),
        ),
    ]
