# Generated by Django 4.2.6 on 2023-10-14 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_booking_customer_inns_overnightstay_restaurant_and_more'),
        ('navigation', '0004_tracker_delete_landmark_delete_marker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackers', to='website.booking'),
        ),
    ]
