# Generated by Django 4.2.6 on 2023-10-28 22:48

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0005_tracker_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(5.0453889387953135, 51.65060519815468), srid=4326),
        ),
    ]
