# Generated by Django 4.2.6 on 2023-10-23 08:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0005_tracker_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obstacle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marker', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('date_placed', models.DateField()),
            ],
        ),
    ]
