# Generated by Django 4.2.6 on 2023-11-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0006_obstacle'),
    ]

    operations = [
        migrations.AddField(
            model_name='obstacle',
            name='description',
            field=models.CharField(default='no description'),
        ),
    ]
