# Generated by Django 4.2.6 on 2023-10-29 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0007_alter_tracker_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
