# Generated by Django 4.2.7 on 2023-11-01 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0007_obstacle_description'),
        ('navigation', '0008_alter_tracker_time'),
    ]

    operations = [
    ]
